services:
  redis:
    image: bitnami/redis:latest
    container_name: redis-warehouse
    ports:
      - "6379:6379"
    restart: unless-stopped
    environment:
      ALLOW_EMPTY_PASSWORD: yes
  postgres:
    image: postgres:latest
    container_name: postgres-warehouse
    environment:
      POSTGRES_USER: worker
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: warehouse-db
    ports:
      - "5432:5432"