server:
  port: 8092
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 5000ms
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse-db
    username: worker
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.cache: DEBUG


